---

- name: Harden firewall udp
  firewalld:
    port: 1025-65535/udp
    permanent: true
    immediate: true
    state: disabled

- name: Harden firewall tcp
  firewalld:
    port: 1025-65535/tcp
    permanent: true
    immediate: true
    state: disabled
