---

- name: Start and enable Docker
  service:
    name: docker
    state: started
    enabled: yes
  when: install_dockerce and autostart_docker

- name: Start and enable tuned
  service:
    name: tuned
    state: started
    enabled: yes

- name: Start and enable thermald
  service:
    name: thermald
    state: started
    enabled: yes
  when: is_laptop
